### ISSUE TITLE
Full Linux Support

### ISSUE THREAD

**Issue by gtsatsis** [zoogie/seedminer#4]
Hey,

I do not know if I am just being a dumdum (It is 5:51AM after all), but it seems like there is no Linux support for seedminer, why's that so? If it isn't already implemented, could it?

(Could anyone like myself make a PR to add Linux support?)

**Comment by zoogie** [comment]
I would be open to a Linux PR, sure.

**Comment by gtsatsis** [comment]
Hey!
I have been trying to do it for the past two days, and I'm getting somewhere! 

If I get a fully-functional version I'll make sure to create a PR!

**Comment by jason0597** [comment]
btw this should be written in c/c++, bruteforcing needs every inch of speed it can get
the python script is just a frontend, the actual bruteforcing is happening behind with the c/c++ code and the opencl code. 
if you want to port it to linux, you need to work with that, not the python front end

**Comment by cajuncooks** [comment]
I built bfcl on Ubuntu 17.10 (cc 7.2.0) with only a handful of changes. I had to download some extra dev libs (libmbedtls-dev and ocl-icd-opencl-dev), make a minor alteration to the Makefile, and adjust some of the C code so it'd compile with -Wall -Werror. Also adjusted the Python front-end to launch bfcl instead of bfcl.exe -- not sure if that could be changed back. I already had proper CUDA drivers installed from other dev work; not sure if that made a difference. Would be happy to share my code, but don't know the best way to go about combining the source... multi-platforming is not my area of expertise at all.

My GTX 1080 took 30 seconds to give a result at 1018.60 M/s, and I tested the injection, works fine.

**Comment by jason0597** [comment]
you can make a PR to [bfcl](https://github.com/Jimmy-Z/bfCL) to give it support for Linux

**Comment by mathew2214** [comment]
if there was linux support, i could get a series of raspberry pi's to help out seedhelper.

**Comment by cajuncook** [comment]
@matthew2214 check out the PR for bfcl as @jason0597 linked. I don't know if CPU mining is optimal for this application, though.

**Comment by jason0597** [comment]
A raspberry pi can not get more than 100H/s
An average GPU can get 800MH/s
This means that you would need (800000)/(100) == 8000 Raspberry Pis in order to match one average graphics card (and we're not even talking about decent graphics cards like the RX 460 and up)

No, Raspberry Pi mining **will never work** 

We haven't even gotten to talking about differences between x86 and ARM and how you'd need to get OpenCL working

**Comment by piratesephiroth** [comment]
it doesn't even run on lower end GPUs, let alone a miniPC, hehe
